//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CustomUIEditor {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class StringsResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringsResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CustomUIEditor.StringsResource", typeof(StringsResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom UI Editor for Microsoft Office.
        /// </summary>
        public static string idsApplicationTitle {
            get {
                return ResourceManager.GetString("idsApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to save changes?.
        /// </summary>
        public static string idsAskForSaveChanges {
            get {
                return ResourceManager.GetString("idsAskForSaveChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change ID.
        /// </summary>
        public static string idsChangeImageId {
            get {
                return ResourceManager.GetString("idsChangeImageId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File {0} has unsaved changes. Do you want to save them before closing it?.
        /// </summary>
        public static string idsCloseWarningMessage {
            get {
                return ResourceManager.GetString("idsCloseWarningMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsaved Changes.
        /// </summary>
        public static string idsCloseWarningTitle {
            get {
                return ResourceManager.GetString("idsCloseWarningTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Col .
        /// </summary>
        public static string idsColumnStatus {
            get {
                return ResourceManager.GetString("idsColumnStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Copy.
        /// </summary>
        public static string idsCopy {
            get {
                return ResourceManager.GetString("idsCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom UI.
        /// </summary>
        public static string idsCustomUI {
            get {
                return ResourceManager.GetString("idsCustomUI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom UI XML namespace must be &quot;{0}&quot;..
        /// </summary>
        public static string idsCustomUINamespace {
            get {
                return ResourceManager.GetString("idsCustomUINamespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cu&amp;t.
        /// </summary>
        public static string idsCut {
            get {
                return ResourceManager.GetString("idsCut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OOXML part Id &quot;{0}&quot; already exists..
        /// </summary>
        public static string idsDuplicateId {
            get {
                return ResourceManager.GetString("idsDuplicateId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Files (*.*)|*.*.
        /// </summary>
        public static string idsFilterAllFiles {
            get {
                return ResourceManager.GetString("idsFilterAllFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OOXML Documents|*.???x;*.???m.
        /// </summary>
        public static string idsFilterAllOfficeDocuments {
            get {
                return ResourceManager.GetString("idsFilterAllOfficeDocuments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supported Icons|*.ico;*.bmp;*.png;*.jpg;*.tif.
        /// </summary>
        public static string idsFilterAllSupportedImages {
            get {
                return ResourceManager.GetString("idsFilterAllSupportedImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft Excel Workbooks|*.xlsx;*.xlsm;*.xlam;*.xltx;*.xltm.
        /// </summary>
        public static string idsFilterExcelDocuments {
            get {
                return ResourceManager.GetString("idsFilterExcelDocuments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft PowerPoint Presentations|*.pp?x;*.pp?m;*.potx;*.potm;*.thmx.
        /// </summary>
        public static string idsFilterPPTDocuments {
            get {
                return ResourceManager.GetString("idsFilterPPTDocuments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excel Workbook|*.xlsx.
        /// </summary>
        public static string idsFilterSaveAs0 {
            get {
                return ResourceManager.GetString("idsFilterSaveAs0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excel Macro-Enabled Workbook|*.xlsm.
        /// </summary>
        public static string idsFilterSaveAs1 {
            get {
                return ResourceManager.GetString("idsFilterSaveAs1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PowerPoint Show|*.ppsx.
        /// </summary>
        public static string idsFilterSaveAs10 {
            get {
                return ResourceManager.GetString("idsFilterSaveAs10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PowerPoint Macro-Enabled Show|*.ppsm.
        /// </summary>
        public static string idsFilterSaveAs11 {
            get {
                return ResourceManager.GetString("idsFilterSaveAs11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PowerPoint Add-in|*.ppam.
        /// </summary>
        public static string idsFilterSaveAs12 {
            get {
                return ResourceManager.GetString("idsFilterSaveAs12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Word Document|*.docx.
        /// </summary>
        public static string idsFilterSaveAs13 {
            get {
                return ResourceManager.GetString("idsFilterSaveAs13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Word Macro-Enabled Document|*.docm.
        /// </summary>
        public static string idsFilterSaveAs14 {
            get {
                return ResourceManager.GetString("idsFilterSaveAs14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Word Template|*.dotx.
        /// </summary>
        public static string idsFilterSaveAs15 {
            get {
                return ResourceManager.GetString("idsFilterSaveAs15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Word Macro-Enabled Template|*.dotm.
        /// </summary>
        public static string idsFilterSaveAs16 {
            get {
                return ResourceManager.GetString("idsFilterSaveAs16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excel Binary Workbook|*.xlsb.
        /// </summary>
        public static string idsFilterSaveAs2 {
            get {
                return ResourceManager.GetString("idsFilterSaveAs2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excel Template|*.xltx.
        /// </summary>
        public static string idsFilterSaveAs3 {
            get {
                return ResourceManager.GetString("idsFilterSaveAs3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excel Macro-Enabled Template|*.xltm.
        /// </summary>
        public static string idsFilterSaveAs4 {
            get {
                return ResourceManager.GetString("idsFilterSaveAs4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excel Add-in|*.xlam.
        /// </summary>
        public static string idsFilterSaveAs5 {
            get {
                return ResourceManager.GetString("idsFilterSaveAs5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PowerPoint Presentation|*.pptx.
        /// </summary>
        public static string idsFilterSaveAs6 {
            get {
                return ResourceManager.GetString("idsFilterSaveAs6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PowerPoint Macro-Enabled Presentation|*.pptm.
        /// </summary>
        public static string idsFilterSaveAs7 {
            get {
                return ResourceManager.GetString("idsFilterSaveAs7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PowerPoint Template|*.potx.
        /// </summary>
        public static string idsFilterSaveAs8 {
            get {
                return ResourceManager.GetString("idsFilterSaveAs8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PowerPoint Macro-Enabled Template|*.potm.
        /// </summary>
        public static string idsFilterSaveAs9 {
            get {
                return ResourceManager.GetString("idsFilterSaveAs9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft Word Documents|*.do?x;*.do?m.
        /// </summary>
        public static string idsFilterWordDocuments {
            get {
                return ResourceManager.GetString("idsFilterWordDocuments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Images.
        /// </summary>
        public static string idsImages {
            get {
                return ResourceManager.GetString("idsImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert Office 2007 Custom UI.
        /// </summary>
        public static string idsInsert12 {
            get {
                return ResourceManager.GetString("idsInsert12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert Office 2010 Custom UI.
        /// </summary>
        public static string idsInsert14 {
            get {
                return ResourceManager.GetString("idsInsert14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert Custom Icons.
        /// </summary>
        public static string idsInsertIconsDialogTitle {
            get {
                return ResourceManager.GetString("idsInsertIconsDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not a valid XML document!.
        /// </summary>
        public static string idsInvalidXml {
            get {
                return ResourceManager.GetString("idsInvalidXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ln .
        /// </summary>
        public static string idsLineStatus {
            get {
                return ResourceManager.GetString("idsLineStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no callback to be generated!.
        /// </summary>
        public static string idsNoCallback {
            get {
                return ResourceManager.GetString("idsNoCallback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target Id cannot be empty..
        /// </summary>
        public static string idsNonEmptyId {
            get {
                return ResourceManager.GetString("idsNonEmptyId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open OOXML Document.
        /// </summary>
        public static string idsOpenDocumentDialogTitle {
            get {
                return ResourceManager.GetString("idsOpenDocumentDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No document is currently opened....
        /// </summary>
        public static string idsOpenDocumentPrompt {
            get {
                return ResourceManager.GetString("idsOpenDocumentPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Paste.
        /// </summary>
        public static string idsPaste {
            get {
                return ResourceManager.GetString("idsPaste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read Only.
        /// </summary>
        public static string idsReadOnly {
            get {
                return ResourceManager.GetString("idsReadOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Redo.
        /// </summary>
        public static string idsRedo {
            get {
                return ResourceManager.GetString("idsRedo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string idsRemoveImage {
            get {
                return ResourceManager.GetString("idsRemoveImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save OOXML Document.
        /// </summary>
        public static string idsSaveDocumentAsDialogTitle {
            get {
                return ResourceManager.GetString("idsSaveDocumentAsDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select &amp;All.
        /// </summary>
        public static string idsSellectAll {
            get {
                return ResourceManager.GetString("idsSellectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Callbacks.
        /// </summary>
        public static string idsTabCallbacks {
            get {
                return ResourceManager.GetString("idsTabCallbacks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom UI.
        /// </summary>
        public static string idsTabCustomUI {
            get {
                return ResourceManager.GetString("idsTabCustomUI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Undo.
        /// </summary>
        public static string idsUndo {
            get {
                return ResourceManager.GetString("idsUndo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown namespace &quot;{0}&quot;..
        /// </summary>
        public static string idsUnknownNamespace {
            get {
                return ResourceManager.GetString("idsUnknownNamespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom UI XML is well formed!.
        /// </summary>
        public static string idsValidXml {
            get {
                return ResourceManager.GetString("idsValidXml", resourceCulture);
            }
        }
    }
}
