//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OfficeRibbonXEditor.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OfficeRibbonXEditor.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author:.
        /// </summary>
        public static string About_Author {
            get {
                return ResourceManager.GetString("About.Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string About_Close {
            get {
                return ResourceManager.GetString("About.Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy version information.
        /// </summary>
        public static string About_CopyVersion {
            get {
                return ResourceManager.GetString("About.CopyVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License:.
        /// </summary>
        public static string About_License {
            get {
                return ResourceManager.GetString("About.License", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operating System:.
        /// </summary>
        public static string About_OperatingSystem {
            get {
                return ResourceManager.GetString("About.OperatingSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Office RibbonX Editor is a free, open source, standalone tool to edit the Custom UI part of Office open document file format. It contains both Office 2007 and Office 2010 custom UI schemas..
        /// </summary>
        public static string About_Paragraph1 {
            get {
                return ResourceManager.GetString("About.Paragraph1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Office 2010 custom UI schema is the latest schema and it&apos;s still being used in the latest versions of Office including Office 2013, Office 2016, Office 2019 and Office 365..
        /// </summary>
        public static string About_Paragraph2 {
            get {
                return ResourceManager.GetString("About.Paragraph2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Page:.
        /// </summary>
        public static string About_ProjectPage {
            get {
                return ResourceManager.GetString("About.ProjectPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Runtime:.
        /// </summary>
        public static string About_Runtime {
            get {
                return ResourceManager.GetString("About.Runtime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit an issue.
        /// </summary>
        public static string About_SubmitIssue {
            get {
                return ResourceManager.GetString("About.SubmitIssue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Office RibbonX Editor.
        /// </summary>
        public static string About_Title {
            get {
                return ResourceManager.GetString("About.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translators:.
        /// </summary>
        public static string About_Translators {
            get {
                return ResourceManager.GetString("About.Translators", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version:.
        /// </summary>
        public static string About_Version {
            get {
                return ResourceManager.GetString("About.Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Callbacks Viewer.
        /// </summary>
        public static string Callbacks_Title {
            get {
                return ResourceManager.GetString("Callbacks.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change ID.
        /// </summary>
        public static string ContextMenu_TreeView_ChangeId {
            get {
                return ResourceManager.GetString("ContextMenu.TreeView.ChangeId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string ContextMenu_TreeView_Close {
            get {
                return ResourceManager.GetString("ContextMenu.TreeView.Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert Icons....
        /// </summary>
        public static string ContextMenu_TreeView_InsertIcons {
            get {
                return ResourceManager.GetString("ContextMenu.TreeView.InsertIcons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert Office 2007 Custom UI Part.
        /// </summary>
        public static string ContextMenu_TreeView_InsertOffice2007 {
            get {
                return ResourceManager.GetString("ContextMenu.TreeView.InsertOffice2007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert Office 2010+ Custom UI Part.
        /// </summary>
        public static string ContextMenu_TreeView_InsertOffice2010 {
            get {
                return ResourceManager.GetString("ContextMenu.TreeView.InsertOffice2010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        public static string ContextMenu_TreeView_Open {
            get {
                return ResourceManager.GetString("ContextMenu.TreeView.Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string ContextMenu_TreeView_Remove {
            get {
                return ResourceManager.GetString("ContextMenu.TreeView.Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string ContextMenu_TreeView_Save {
            get {
                return ResourceManager.GetString("ContextMenu.TreeView.Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save As....
        /// </summary>
        public static string ContextMenu_TreeView_SaveAs {
            get {
                return ResourceManager.GetString("ContextMenu.TreeView.SaveAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom Factor:.
        /// </summary>
        public static string Editor_ZoomFactor {
            get {
                return ResourceManager.GetString("Editor.ZoomFactor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close this Dialog.
        /// </summary>
        public static string Exception_CloseDialog {
            get {
                return ResourceManager.GetString("Exception.CloseDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you keep using the tool after this exception, it might start to malfunction..
        /// </summary>
        public static string Exception_Disclaimer {
            get {
                return ResourceManager.GetString("Exception.Disclaimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shutdown Application.
        /// </summary>
        public static string Exception_ShutdownApp {
            get {
                return ResourceManager.GetString("Exception.ShutdownApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit Bug Report.
        /// </summary>
        public static string Exception_SubmitBug {
            get {
                return ResourceManager.GetString("Exception.SubmitBug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unhandled Exception Occurred.
        /// </summary>
        public static string Exception_Title {
            get {
                return ResourceManager.GetString("Exception.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Files (*.*)|*.*.
        /// </summary>
        public static string Filter_All {
            get {
                return ResourceManager.GetString("Filter.All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Office Documents|*.???x;*.???m.
        /// </summary>
        public static string Filter_AllOfficeDocuments {
            get {
                return ResourceManager.GetString("Filter.AllOfficeDocuments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft Excel Workbooks|*.xlsx;*.xlsm;*.xlam;*.xltx;*.xltm.
        /// </summary>
        public static string Filter_ExcelDocuments {
            get {
                return ResourceManager.GetString("Filter.ExcelDocuments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supported Icons|*.ico;*.bmp;*.png;*.jpg;*.tif.
        /// </summary>
        public static string Filter_Icons {
            get {
                return ResourceManager.GetString("Filter.Icons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft PowerPoint Presentations|*.pp?x;*.pp?m;*.potx;*.potm;*.thmx.
        /// </summary>
        public static string Filter_PowerPointDocuments {
            get {
                return ResourceManager.GetString("Filter.PowerPointDocuments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excel Workbook|*.xlsx.
        /// </summary>
        public static string Filter_SaveAs0 {
            get {
                return ResourceManager.GetString("Filter.SaveAs0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excel Macro-Enabled Workbook|*.xlsm.
        /// </summary>
        public static string Filter_SaveAs1 {
            get {
                return ResourceManager.GetString("Filter.SaveAs1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PowerPoint Show|*.ppsx.
        /// </summary>
        public static string Filter_SaveAs10 {
            get {
                return ResourceManager.GetString("Filter.SaveAs10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PowerPoint Macro-Enabled Show|*.ppsm.
        /// </summary>
        public static string Filter_SaveAs11 {
            get {
                return ResourceManager.GetString("Filter.SaveAs11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PowerPoint Add-in|*.ppam.
        /// </summary>
        public static string Filter_SaveAs12 {
            get {
                return ResourceManager.GetString("Filter.SaveAs12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Word Document|*.docx.
        /// </summary>
        public static string Filter_SaveAs13 {
            get {
                return ResourceManager.GetString("Filter.SaveAs13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Word Macro-Enabled Document|*.docm.
        /// </summary>
        public static string Filter_SaveAs14 {
            get {
                return ResourceManager.GetString("Filter.SaveAs14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Word Template|*.dotx.
        /// </summary>
        public static string Filter_SaveAs15 {
            get {
                return ResourceManager.GetString("Filter.SaveAs15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Word Macro-Enabled Template|*.dotm.
        /// </summary>
        public static string Filter_SaveAs16 {
            get {
                return ResourceManager.GetString("Filter.SaveAs16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visio Diagram|*.vsdx.
        /// </summary>
        public static string Filter_SaveAs17 {
            get {
                return ResourceManager.GetString("Filter.SaveAs17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visio Macro-Enabled Diagram|*.vsdm.
        /// </summary>
        public static string Filter_SaveAs18 {
            get {
                return ResourceManager.GetString("Filter.SaveAs18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visio Template|*.vstx.
        /// </summary>
        public static string Filter_SaveAs19 {
            get {
                return ResourceManager.GetString("Filter.SaveAs19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excel Binary Workbook|*.xlsb.
        /// </summary>
        public static string Filter_SaveAs2 {
            get {
                return ResourceManager.GetString("Filter.SaveAs2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visio Macro-Enabled Template|*.vstm.
        /// </summary>
        public static string Filter_SaveAs20 {
            get {
                return ResourceManager.GetString("Filter.SaveAs20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excel Template|*.xltx.
        /// </summary>
        public static string Filter_SaveAs3 {
            get {
                return ResourceManager.GetString("Filter.SaveAs3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excel Macro-Enabled Template|*.xltm.
        /// </summary>
        public static string Filter_SaveAs4 {
            get {
                return ResourceManager.GetString("Filter.SaveAs4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excel Add-in|*.xlam.
        /// </summary>
        public static string Filter_SaveAs5 {
            get {
                return ResourceManager.GetString("Filter.SaveAs5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PowerPoint Presentation|*.pptx.
        /// </summary>
        public static string Filter_SaveAs6 {
            get {
                return ResourceManager.GetString("Filter.SaveAs6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PowerPoint Macro-Enabled Presentation|*.pptm.
        /// </summary>
        public static string Filter_SaveAs7 {
            get {
                return ResourceManager.GetString("Filter.SaveAs7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PowerPoint Template|*.potx.
        /// </summary>
        public static string Filter_SaveAs8 {
            get {
                return ResourceManager.GetString("Filter.SaveAs8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PowerPoint Macro-Enabled Template|*.potm.
        /// </summary>
        public static string Filter_SaveAs9 {
            get {
                return ResourceManager.GetString("Filter.SaveAs9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft Visio Drawings|*.vsdx;*.vsdm;*.vstx;*.vstm;*.vssx;*.vssm;.
        /// </summary>
        public static string Filter_VisioDocuments {
            get {
                return ResourceManager.GetString("Filter.VisioDocuments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft Word Documents|*.do?x;*.do?m.
        /// </summary>
        public static string Filter_WordDocuments {
            get {
                return ResourceManager.GetString("Filter.WordDocuments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Find.
        /// </summary>
        public static string FindReplace_Find {
            get {
                return ResourceManager.GetString("FindReplace.Find", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find All.
        /// </summary>
        public static string FindReplace_FindAll {
            get {
                return ResourceManager.GetString("FindReplace.FindAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C_lear.
        /// </summary>
        public static string FindReplace_FindAll_Clear {
            get {
                return ResourceManager.GetString("FindReplace.FindAll.Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Highlight Matches.
        /// </summary>
        public static string FindReplace_FindAll_HighlightMatches {
            get {
                return ResourceManager.GetString("FindReplace.FindAll.HighlightMatches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Mark Line.
        /// </summary>
        public static string FindReplace_FindAll_MarkLine {
            get {
                return ResourceManager.GetString("FindReplace.FindAll.MarkLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find _All.
        /// </summary>
        public static string FindReplace_FindAll_Ok {
            get {
                return ResourceManager.GetString("FindReplace.FindAll.Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find Next.
        /// </summary>
        public static string FindReplace_FindNext {
            get {
                return ResourceManager.GetString("FindReplace.FindNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find Previous.
        /// </summary>
        public static string FindReplace_FindPrevious {
            get {
                return ResourceManager.GetString("FindReplace.FindPrevious", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find.
        /// </summary>
        public static string FindReplace_FindTab {
            get {
                return ResourceManager.GetString("FindReplace.FindTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        public static string FindReplace_Options {
            get {
                return ResourceManager.GetString("FindReplace.Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Compiled.
        /// </summary>
        public static string FindReplace_Options_Compiled {
            get {
                return ResourceManager.GetString("FindReplace.Options.Compiled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ECMAScript.
        /// </summary>
        public static string FindReplace_Options_ECMAScript {
            get {
                return ResourceManager.GetString("FindReplace.Options.ECMAScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E_xplicit Capture.
        /// </summary>
        public static string FindReplace_Options_ExplicitCapture {
            get {
                return ResourceManager.GetString("FindReplace.Options.ExplicitCapture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I_gnore Case.
        /// </summary>
        public static string FindReplace_Options_IgnoreCase {
            get {
                return ResourceManager.GetString("FindReplace.Options.IgnoreCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignore Pattern Whitespace.
        /// </summary>
        public static string FindReplace_Options_IgnoreWhitespace {
            get {
                return ResourceManager.GetString("FindReplace.Options.IgnoreWhitespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C_ulture Invariant.
        /// </summary>
        public static string FindReplace_Options_Invariant {
            get {
                return ResourceManager.GetString("FindReplace.Options.Invariant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiline.
        /// </summary>
        public static string FindReplace_Options_Multiline {
            get {
                return ResourceManager.GetString("FindReplace.Options.Multiline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right To Left.
        /// </summary>
        public static string FindReplace_Options_RightToLeft {
            get {
                return ResourceManager.GetString("FindReplace.Options.RightToLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Singleline.
        /// </summary>
        public static string FindReplace_Options_Singleline {
            get {
                return ResourceManager.GetString("FindReplace.Options.Singleline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Replace.
        /// </summary>
        public static string FindReplace_Replace {
            get {
                return ResourceManager.GetString("FindReplace.Replace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace _All.
        /// </summary>
        public static string FindReplace_ReplaceAll {
            get {
                return ResourceManager.GetString("FindReplace.ReplaceAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace _Next.
        /// </summary>
        public static string FindReplace_ReplaceNext {
            get {
                return ResourceManager.GetString("FindReplace.ReplaceNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace _Previous.
        /// </summary>
        public static string FindReplace_ReplacePrevious {
            get {
                return ResourceManager.GetString("FindReplace.ReplacePrevious", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace.
        /// </summary>
        public static string FindReplace_ReplaceTab {
            get {
                return ResourceManager.GetString("FindReplace.ReplaceTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Type.
        /// </summary>
        public static string FindReplace_SearchType {
            get {
                return ResourceManager.GetString("FindReplace.SearchType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E_xtended (\n, \r, \t, \0).
        /// </summary>
        public static string FindReplace_SearchType_Extended {
            get {
                return ResourceManager.GetString("FindReplace.SearchType.Extended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regular _Expression.
        /// </summary>
        public static string FindReplace_SearchType_Regular {
            get {
                return ResourceManager.GetString("FindReplace.SearchType.Regular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Standard.
        /// </summary>
        public static string FindReplace_SearchType_Standard {
            get {
                return ResourceManager.GetString("FindReplace.SearchType.Standard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Selection.
        /// </summary>
        public static string FindReplace_Selection {
            get {
                return ResourceManager.GetString("FindReplace.Selection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Match could not be found.
        /// </summary>
        public static string FindReplace_Status_NoMatch {
            get {
                return ResourceManager.GetString("FindReplace.Status.NoMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error in Regular Expression.
        /// </summary>
        public static string FindReplace_Status_RegExError {
            get {
                return ResourceManager.GetString("FindReplace.Status.RegExError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total found.
        /// </summary>
        public static string FindReplace_Status_TotalFound {
            get {
                return ResourceManager.GetString("FindReplace.Status.TotalFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total replaced.
        /// </summary>
        public static string FindReplace_Status_TotalReplaced {
            get {
                return ResourceManager.GetString("FindReplace.Status.TotalReplaced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search match wrapped to the beginning of the document / selection.
        /// </summary>
        public static string FindReplace_Status_Wrap {
            get {
                return ResourceManager.GetString("FindReplace.Status.Wrap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find and Replace.
        /// </summary>
        public static string FindReplace_Title {
            get {
                return ResourceManager.GetString("FindReplace.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Wrap.
        /// </summary>
        public static string FindReplace_Wrap {
            get {
                return ResourceManager.GetString("FindReplace.Wrap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string GoTo_Cancel {
            get {
                return ResourceManager.GetString("GoTo.Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Current line number.
        /// </summary>
        public static string GoTo_CurrentLine {
            get {
                return ResourceManager.GetString("GoTo.CurrentLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to line number.
        /// </summary>
        public static string GoTo_DesiredLine {
            get {
                return ResourceManager.GetString("GoTo.DesiredLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Maximum line number.
        /// </summary>
        public static string GoTo_MaxLine {
            get {
                return ResourceManager.GetString("GoTo.MaxLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string GoTo_Ok {
            get {
                return ResourceManager.GetString("GoTo.Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go To Line.
        /// </summary>
        public static string GoTo_Title {
            get {
                return ResourceManager.GetString("GoTo.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Office RibbonX Editor.
        /// </summary>
        public static string MainWindow_Title {
            get {
                return ResourceManager.GetString("MainWindow.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Edit.
        /// </summary>
        public static string Menu_Edit {
            get {
                return ResourceManager.GetString("Menu.Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        public static string Menu_Edit_Copy {
            get {
                return ResourceManager.GetString("Menu.Edit.Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cut.
        /// </summary>
        public static string Menu_Edit_Cut {
            get {
                return ResourceManager.GetString("Menu.Edit.Cut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate Line.
        /// </summary>
        public static string Menu_Edit_DuplicateLine {
            get {
                return ResourceManager.GetString("Menu.Edit.DuplicateLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find....
        /// </summary>
        public static string Menu_Edit_Find {
            get {
                return ResourceManager.GetString("Menu.Edit.Find", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find Next.
        /// </summary>
        public static string Menu_Edit_FindNext {
            get {
                return ResourceManager.GetString("Menu.Edit.FindNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find Previous.
        /// </summary>
        public static string Menu_Edit_FindPrevious {
            get {
                return ResourceManager.GetString("Menu.Edit.FindPrevious", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go To Line....
        /// </summary>
        public static string Menu_Edit_GoTo {
            get {
                return ResourceManager.GetString("Menu.Edit.GoTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incremental Search....
        /// </summary>
        public static string Menu_Edit_Incremental {
            get {
                return ResourceManager.GetString("Menu.Edit.Incremental", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste.
        /// </summary>
        public static string Menu_Edit_Paste {
            get {
                return ResourceManager.GetString("Menu.Edit.Paste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redo.
        /// </summary>
        public static string Menu_Edit_Redo {
            get {
                return ResourceManager.GetString("Menu.Edit.Redo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace....
        /// </summary>
        public static string Menu_Edit_Replace {
            get {
                return ResourceManager.GetString("Menu.Edit.Replace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select All.
        /// </summary>
        public static string Menu_Edit_SelectAll {
            get {
                return ResourceManager.GetString("Menu.Edit.SelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undo.
        /// </summary>
        public static string Menu_Edit_Undo {
            get {
                return ResourceManager.GetString("Menu.Edit.Undo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _File.
        /// </summary>
        public static string Menu_File {
            get {
                return ResourceManager.GetString("Menu.File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close Current Document.
        /// </summary>
        public static string Menu_File_Close {
            get {
                return ResourceManager.GetString("Menu.File.Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string Menu_File_Exit {
            get {
                return ResourceManager.GetString("Menu.File.Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        public static string Menu_File_Open {
            get {
                return ResourceManager.GetString("Menu.File.Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Current Document.
        /// </summary>
        public static string Menu_File_Save {
            get {
                return ResourceManager.GetString("Menu.File.Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save All Documents.
        /// </summary>
        public static string Menu_File_SaveAll {
            get {
                return ResourceManager.GetString("Menu.File.SaveAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save As....
        /// </summary>
        public static string Menu_File_SaveAs {
            get {
                return ResourceManager.GetString("Menu.File.SaveAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save the current document with a different name.
        /// </summary>
        public static string Menu_File_SaveAs_ToolTip {
            get {
                return ResourceManager.GetString("Menu.File.SaveAs.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save a Copy As....
        /// </summary>
        public static string Menu_FIle_SaveCopy {
            get {
                return ResourceManager.GetString("Menu.FIle.SaveCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save a completely separate copy of the current document.
        /// </summary>
        public static string Menu_File_SaveCopy_ToolTip {
            get {
                return ResourceManager.GetString("Menu.File.SaveCopy.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings....
        /// </summary>
        public static string Menu_File_Settings {
            get {
                return ResourceManager.GetString("Menu.File.Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Help.
        /// </summary>
        public static string Menu_Help {
            get {
                return ResourceManager.GetString("Menu.Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string Menu_Help_About {
            get {
                return ResourceManager.GetString("Menu.Help.About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Useful Links.
        /// </summary>
        public static string Menu_Help_UsefulLinks {
            get {
                return ResourceManager.GetString("Menu.Help.UsefulLinks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Insert.
        /// </summary>
        public static string Menu_Insert {
            get {
                return ResourceManager.GetString("Menu.Insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Icons....
        /// </summary>
        public static string Menu_Insert_Icons {
            get {
                return ResourceManager.GetString("Menu.Insert.Icons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Office 2007 Custom UI Part.
        /// </summary>
        public static string Menu_Insert_Office2007 {
            get {
                return ResourceManager.GetString("Menu.Insert.Office2007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Office 2010+ Custom UI Part.
        /// </summary>
        public static string Menu_Insert_Office2010 {
            get {
                return ResourceManager.GetString("Menu.Insert.Office2010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sample XML.
        /// </summary>
        public static string Menu_Insert_Sample {
            get {
                return ResourceManager.GetString("Menu.Insert.Sample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _View.
        /// </summary>
        public static string Menu_View {
            get {
                return ResourceManager.GetString("Menu.View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fold All.
        /// </summary>
        public static string Menu_View_FoldAll {
            get {
                return ResourceManager.GetString("Menu.View.FoldAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fold Current Level.
        /// </summary>
        public static string Menu_View_FoldCurrent {
            get {
                return ResourceManager.GetString("Menu.View.FoldCurrent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fold Level.
        /// </summary>
        public static string Menu_View_FoldLevel {
            get {
                return ResourceManager.GetString("Menu.View.FoldLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unfold All.
        /// </summary>
        public static string Menu_View_UnfoldAll {
            get {
                return ResourceManager.GetString("Menu.View.UnfoldAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unfold Current Level.
        /// </summary>
        public static string Menu_View_UnfoldCurrent {
            get {
                return ResourceManager.GetString("Menu.View.UnfoldCurrent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unfold Level.
        /// </summary>
        public static string Menu_View_UnfoldLevel {
            get {
                return ResourceManager.GetString("Menu.View.UnfoldLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The document &apos;{0}&apos; is already open. Opening a document more than once is dangerous and can lead to loss of data, unless you save it with a different name straight away.
        ///
        ///Are you completely sure you want to open this document again?.
        /// </summary>
        public static string Message_AlreadyOpen_Text {
            get {
                return ResourceManager.GetString("Message.AlreadyOpen.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document Already Open.
        /// </summary>
        public static string Message_AlreadyOpen_Title {
            get {
                return ResourceManager.GetString("Message.AlreadyOpen.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Generating Callbacks.
        /// </summary>
        public static string Message_CallbackError_Title {
            get {
                return ResourceManager.GetString("Message.CallbackError.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Changing Icon ID.
        /// </summary>
        public static string Message_ChangeIdError_Title {
            get {
                return ResourceManager.GetString("Message.ChangeIdError.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File {0} has unsaved changes. Do you want to save them before closing it?.
        /// </summary>
        public static string Message_CloseUnsavedDoc_Text {
            get {
                return ResourceManager.GetString("Message.CloseUnsavedDoc.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsaved Changes.
        /// </summary>
        public static string Message_CloseUnsavedDoc_Title {
            get {
                return ResourceManager.GetString("Message.CloseUnsavedDoc.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user settings file at the following location is corrupted and cannot be deleted:
        ///
        ///{0}
        ///
        ///Please delete this file manually and restart the app. Its folder location has been copied to the clipboard..
        /// </summary>
        public static string Message_CorruptedSettings_Text {
            get {
                return ResourceManager.GetString("Message.CorruptedSettings.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Corrupted Settings.
        /// </summary>
        public static string Message_CorruptedSettings_Title {
            get {
                return ResourceManager.GetString("Message.CorruptedSettings.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This custom UI file already has an icon with id {0}. Do you want to insert the new icon with id {1} instead?.
        /// </summary>
        public static string Message_IconExists_Text {
            get {
                return ResourceManager.GetString("Message.IconExists.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Icon Already Exists.
        /// </summary>
        public static string Message_IconExists_Title {
            get {
                return ResourceManager.GetString("Message.IconExists.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This will insert the sample XML code on the current cursor position. Are you sure you want to continue?.
        /// </summary>
        public static string Message_InsertSample_Text {
            get {
                return ResourceManager.GetString("Message.InsertSample.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert XML Sample.
        /// </summary>
        public static string Message_InsertSample_Title {
            get {
                return ResourceManager.GetString("Message.InsertSample.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error inserting XML sample.
        /// </summary>
        public static string Message_InsertSampleError_Title {
            get {
                return ResourceManager.GetString("Message.InsertSampleError.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Release version {0} is now available. Do you want to download it?.
        /// </summary>
        public static string Message_NewVersion_Text {
            get {
                return ResourceManager.GetString("Message.NewVersion.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Newer Version Available.
        /// </summary>
        public static string Message_NewVersion_Title {
            get {
                return ResourceManager.GetString("Message.NewVersion.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no callback to be generated..
        /// </summary>
        public static string Message_NoCallbacks_Text {
            get {
                return ResourceManager.GetString("Message.NoCallbacks.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate Callbacks.
        /// </summary>
        public static string Message_NoCallbacks_Title {
            get {
                return ResourceManager.GetString("Message.NoCallbacks.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error opening Office document.
        /// </summary>
        public static string Message_OpenError_Title {
            get {
                return ResourceManager.GetString("Message.OpenError.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This action cannot be undone. Are you sure you want to continue?.
        /// </summary>
        public static string Message_RemoveIcon_Text {
            get {
                return ResourceManager.GetString("Message.RemoveIcon.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Icon.
        /// </summary>
        public static string Message_RemoveIcon_Title {
            get {
                return ResourceManager.GetString("Message.RemoveIcon.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This action cannot be undone. Are you sure you want to continue?.
        /// </summary>
        public static string Message_RemovePart_Text {
            get {
                return ResourceManager.GetString("Message.RemovePart.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove XML part.
        /// </summary>
        public static string Message_RemovePart_Title {
            get {
                return ResourceManager.GetString("Message.RemovePart.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error saving Office document.
        /// </summary>
        public static string Message_SaveError_Title {
            get {
                return ResourceManager.GetString("Message.SaveError.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom UI XML is well formed..
        /// </summary>
        public static string Message_ValidXml_Text {
            get {
                return ResourceManager.GetString("Message.ValidXml.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XML is Valid.
        /// </summary>
        public static string Message_ValidXml_Title {
            get {
                return ResourceManager.GetString("Message.ValidXml.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The version information has been copied to the clipboard..
        /// </summary>
        public static string Message_VersionCopy_Text {
            get {
                return ResourceManager.GetString("Message.VersionCopy.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version Information Copied.
        /// </summary>
        public static string Message_VersionCopy_Title {
            get {
                return ResourceManager.GetString("Message.VersionCopy.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open OOXML Document.
        /// </summary>
        public static string OpenDialog_Document_Title {
            get {
                return ResourceManager.GetString("OpenDialog.Document.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert Custom Icons.
        /// </summary>
        public static string OpenDialog_Icons_Title {
            get {
                return ResourceManager.GetString("OpenDialog.Icons.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save OOXML Document.
        /// </summary>
        public static string SaveDialog_SaveAs_Title {
            get {
                return ResourceManager.GetString("SaveDialog.SaveAs.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept.
        /// </summary>
        public static string Settings_Accept {
            get {
                return ResourceManager.GetString("Settings.Accept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        public static string Settings_Apply {
            get {
                return ResourceManager.GetString("Settings.Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editor colors.
        /// </summary>
        public static string Settings_Colors {
            get {
                return ResourceManager.GetString("Settings.Colors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attribute.
        /// </summary>
        public static string Settings_Colors_Attribute {
            get {
                return ResourceManager.GetString("Settings.Colors.Attribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background.
        /// </summary>
        public static string Settings_Colors_Background {
            get {
                return ResourceManager.GetString("Settings.Colors.Background", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment.
        /// </summary>
        public static string Settings_Colors_Comment {
            get {
                return ResourceManager.GetString("Settings.Colors.Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal Text.
        /// </summary>
        public static string Settings_Colors_Default {
            get {
                return ResourceManager.GetString("Settings.Colors.Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to String.
        /// </summary>
        public static string Settings_Colors_String {
            get {
                return ResourceManager.GetString("Settings.Colors.String", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag.
        /// </summary>
        public static string Settings_Colors_Tag {
            get {
                return ResourceManager.GetString("Settings.Colors.Tag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other editor settings.
        /// </summary>
        public static string Settings_Editor {
            get {
                return ResourceManager.GetString("Settings.Editor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto-indent new lines.
        /// </summary>
        public static string Settings_Editor_AutoIndent {
            get {
                return ResourceManager.GetString("Settings.Editor.AutoIndent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font Size.
        /// </summary>
        public static string Settings_Editor_FontSize {
            get {
                return ResourceManager.GetString("Settings.Editor.FontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tab Width.
        /// </summary>
        public static string Settings_Editor_TabWidth {
            get {
                return ResourceManager.GetString("Settings.Editor.TabWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrap Mode.
        /// </summary>
        public static string Settings_Editor_WrapMode {
            get {
                return ResourceManager.GetString("Settings.Editor.WrapMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Associations.
        /// </summary>
        public static string Settings_FileAssociations {
            get {
                return ResourceManager.GetString("Settings.FileAssociations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check All.
        /// </summary>
        public static string Settings_FileAssociations_CheckAll {
            get {
                return ResourceManager.GetString("Settings.FileAssociations.CheckAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A context menu entry will appear in Windows Explorer to edit these files directly with the tool.
        /// </summary>
        public static string Settings_FileAssociations_ToolTip {
            get {
                return ResourceManager.GetString("Settings.FileAssociations.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uncheck All.
        /// </summary>
        public static string Settings_FileAssociations_UncheckAll {
            get {
                return ResourceManager.GetString("Settings.FileAssociations.UncheckAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Misc.
        /// </summary>
        public static string Settings_Misc {
            get {
                return ResourceManager.GetString("Settings.Misc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show default XML templates in the Insert menu.
        /// </summary>
        public static string Settings_Misc_DefaultTemplates {
            get {
                return ResourceManager.GetString("Settings.Misc.DefaultTemplates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional XML templates to load:.
        /// </summary>
        public static string Settings_Misc_ExtraTemplates {
            get {
                return ResourceManager.GetString("Settings.Misc.ExtraTemplates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One path per line. Paths can be either XML files or folders containing those. They can also be relative to the tool&apos;s folder.
        /// </summary>
        public static string Settings_Misc_ExtraTemplates_ToolTip {
            get {
                return ResourceManager.GetString("Settings.Misc.ExtraTemplates.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Settings_Misc_Language {
            get {
                return ResourceManager.GetString("Settings.Misc.Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preserve file attributes when saving an already existing document.
        /// </summary>
        public static string Settings_Misc_PreserveAttributes {
            get {
                return ResourceManager.GetString("Settings.Misc.PreserveAttributes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If checked, read-only files will keep to be read-only after saving them for example.
        /// </summary>
        public static string Settings_Misc_PreserveAttributes_ToolTip {
            get {
                return ResourceManager.GetString("Settings.Misc.PreserveAttributes.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Defaults.
        /// </summary>
        public static string Settings_ResetDefaults {
            get {
                return ResourceManager.GetString("Settings.ResetDefaults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings_Title {
            get {
                return ResourceManager.GetString("Settings.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate Callbacks.
        /// </summary>
        public static string ToolBar_Callbacks {
            get {
                return ResourceManager.GetString("ToolBar.Callbacks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate callbacks for the current XML file.
        /// </summary>
        public static string ToolBar_Callbacks_ToolTip {
            get {
                return ResourceManager.GetString("ToolBar.Callbacks.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert Icons.
        /// </summary>
        public static string ToolBar_InsertIcons {
            get {
                return ResourceManager.GetString("ToolBar.InsertIcons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert Icons.
        /// </summary>
        public static string ToolBar_InsertIcons_ToolTip {
            get {
                return ResourceManager.GetString("ToolBar.InsertIcons.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        public static string ToolBar_Open {
            get {
                return ResourceManager.GetString("ToolBar.Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open an Office document.
        /// </summary>
        public static string ToolBar_Open_ToolTip {
            get {
                return ResourceManager.GetString("ToolBar.Open.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reload on Save.
        /// </summary>
        public static string ToolBar_ReloadOnSave {
            get {
                return ResourceManager.GetString("ToolBar.ReloadOnSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To ensure you do not delete changes made externally, you can reload the documents right before they are to be saved.
        /// </summary>
        public static string ToolBar_ReloadOnSave_ToolTip {
            get {
                return ResourceManager.GetString("ToolBar.ReloadOnSave.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string ToolBar_Save {
            get {
                return ResourceManager.GetString("ToolBar.Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save the current Office document.
        /// </summary>
        public static string ToolBar_Save_ToolTip {
            get {
                return ResourceManager.GetString("ToolBar.Save.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string ToolBar_Settings {
            get {
                return ResourceManager.GetString("ToolBar.Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View the editor settings.
        /// </summary>
        public static string ToolBar_Settings_ToolTip {
            get {
                return ResourceManager.GetString("ToolBar.Settings.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show space, tab and line end characters in the editor.
        /// </summary>
        public static string ToolBar_ShowWhitespaces_ToolTip {
            get {
                return ResourceManager.GetString("ToolBar.ShowWhitespaces.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment / uncomment the currently selected lines.
        /// </summary>
        public static string ToolBar_ToggleComment_ToolTip {
            get {
                return ResourceManager.GetString("ToolBar.ToggleComment.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validate.
        /// </summary>
        public static string ToolBar_Validate {
            get {
                return ResourceManager.GetString("ToolBar.Validate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check whether the current XML file conforms to its corresponding schema.
        /// </summary>
        public static string ToolBar_Validate_ToolTip {
            get {
                return ResourceManager.GetString("ToolBar.Validate.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to v{0} Available!.
        /// </summary>
        public static string ToolBar_VersionAvailable {
            get {
                return ResourceManager.GetString("ToolBar.VersionAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can only define one of the following attributes in an element: {0}.
        /// </summary>
        public static string Validation_MutuallyExclusive {
            get {
                return ResourceManager.GetString("Validation.MutuallyExclusive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown namespace &quot;{0}&quot;. Custom UI XML namespace must be &quot;{1}&quot;.
        /// </summary>
        public static string Validation_WrongNamespace {
            get {
                return ResourceManager.GetString("Validation.WrongNamespace", resourceCulture);
            }
        }
    }
}
