//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OfficeRibbonXEditor.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OfficeRibbonXEditor.Properties.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Edit.
        /// </summary>
        public static string Menu_Edit {
            get {
                return ResourceManager.GetString("Menu.Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        public static string Menu_Edit_Copy {
            get {
                return ResourceManager.GetString("Menu.Edit.Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cut.
        /// </summary>
        public static string Menu_Edit_Cut {
            get {
                return ResourceManager.GetString("Menu.Edit.Cut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find....
        /// </summary>
        public static string Menu_Edit_Find {
            get {
                return ResourceManager.GetString("Menu.Edit.Find", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find Next.
        /// </summary>
        public static string Menu_Edit_FindNext {
            get {
                return ResourceManager.GetString("Menu.Edit.FindNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find Previous.
        /// </summary>
        public static string Menu_Edit_FindPrevious {
            get {
                return ResourceManager.GetString("Menu.Edit.FindPrevious", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go To Line....
        /// </summary>
        public static string Menu_Edit_GoTo {
            get {
                return ResourceManager.GetString("Menu.Edit.GoTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incremental Search....
        /// </summary>
        public static string Menu_Edit_Incremental {
            get {
                return ResourceManager.GetString("Menu.Edit.Incremental", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste.
        /// </summary>
        public static string Menu_Edit_Paste {
            get {
                return ResourceManager.GetString("Menu.Edit.Paste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redo.
        /// </summary>
        public static string Menu_Edit_Redo {
            get {
                return ResourceManager.GetString("Menu.Edit.Redo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace....
        /// </summary>
        public static string Menu_Edit_Replace {
            get {
                return ResourceManager.GetString("Menu.Edit.Replace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select All.
        /// </summary>
        public static string Menu_Edit_SelectAll {
            get {
                return ResourceManager.GetString("Menu.Edit.SelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undo.
        /// </summary>
        public static string Menu_Edit_Undo {
            get {
                return ResourceManager.GetString("Menu.Edit.Undo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _File.
        /// </summary>
        public static string Menu_File {
            get {
                return ResourceManager.GetString("Menu.File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close Current Document.
        /// </summary>
        public static string Menu_File_Close {
            get {
                return ResourceManager.GetString("Menu.File.Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string Menu_File_Exit {
            get {
                return ResourceManager.GetString("Menu.File.Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        public static string Menu_File_Open {
            get {
                return ResourceManager.GetString("Menu.File.Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Current Document.
        /// </summary>
        public static string Menu_File_Save {
            get {
                return ResourceManager.GetString("Menu.File.Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save All Documents.
        /// </summary>
        public static string Menu_File_SaveAll {
            get {
                return ResourceManager.GetString("Menu.File.SaveAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save As....
        /// </summary>
        public static string Menu_File_SaveAs {
            get {
                return ResourceManager.GetString("Menu.File.SaveAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save the current document with a different name.
        /// </summary>
        public static string Menu_File_SaveAs_ToolTip {
            get {
                return ResourceManager.GetString("Menu.File.SaveAs.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save a Copy As....
        /// </summary>
        public static string Menu_FIle_SaveCopy {
            get {
                return ResourceManager.GetString("Menu.FIle.SaveCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save a completely separate copy of the current document.
        /// </summary>
        public static string Menu_File_SaveCopy_ToolTip {
            get {
                return ResourceManager.GetString("Menu.File.SaveCopy.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings....
        /// </summary>
        public static string Menu_File_Settings {
            get {
                return ResourceManager.GetString("Menu.File.Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Help.
        /// </summary>
        public static string Menu_Help {
            get {
                return ResourceManager.GetString("Menu.Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Useful Links.
        /// </summary>
        public static string Menu_Help_UsefulLinks {
            get {
                return ResourceManager.GetString("Menu.Help.UsefulLinks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Insert.
        /// </summary>
        public static string Menu_Insert {
            get {
                return ResourceManager.GetString("Menu.Insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Icons....
        /// </summary>
        public static string Menu_Insert_Icons {
            get {
                return ResourceManager.GetString("Menu.Insert.Icons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Office 2007 Custom UI Part.
        /// </summary>
        public static string Menu_Insert_Office2007 {
            get {
                return ResourceManager.GetString("Menu.Insert.Office2007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Office 2010+ Custom UI Part.
        /// </summary>
        public static string Menu_Insert_Office2010 {
            get {
                return ResourceManager.GetString("Menu.Insert.Office2010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sample XML.
        /// </summary>
        public static string Menu_Insert_Sample {
            get {
                return ResourceManager.GetString("Menu.Insert.Sample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _View.
        /// </summary>
        public static string Menu_View {
            get {
                return ResourceManager.GetString("Menu.View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fold All.
        /// </summary>
        public static string Menu_View_FoldAll {
            get {
                return ResourceManager.GetString("Menu.View.FoldAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fold Current Level.
        /// </summary>
        public static string Menu_View_FoldCurrent {
            get {
                return ResourceManager.GetString("Menu.View.FoldCurrent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fold Level.
        /// </summary>
        public static string Menu_View_FoldLevel {
            get {
                return ResourceManager.GetString("Menu.View.FoldLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UnfoldAll.
        /// </summary>
        public static string Menu_View_UnfoldAll {
            get {
                return ResourceManager.GetString("Menu.View.UnfoldAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unfold Current Level.
        /// </summary>
        public static string Menu_View_UnfoldCurrent {
            get {
                return ResourceManager.GetString("Menu.View.UnfoldCurrent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unfold Level.
        /// </summary>
        public static string Menu_View_UnfoldLevel {
            get {
                return ResourceManager.GetString("Menu.View.UnfoldLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate Callbacks.
        /// </summary>
        public static string ToolBar_Callbacks {
            get {
                return ResourceManager.GetString("ToolBar.Callbacks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate callbacks for the current XML file.
        /// </summary>
        public static string ToolBar_Callbacks_ToolTip {
            get {
                return ResourceManager.GetString("ToolBar.Callbacks.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert Icons.
        /// </summary>
        public static string ToolBar_InsertIcons {
            get {
                return ResourceManager.GetString("ToolBar.InsertIcons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert Icons.
        /// </summary>
        public static string ToolBar_InsertIcons_ToolTip {
            get {
                return ResourceManager.GetString("ToolBar.InsertIcons.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        public static string ToolBar_Open {
            get {
                return ResourceManager.GetString("ToolBar.Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open an Office document.
        /// </summary>
        public static string ToolBar_Open_ToolTip {
            get {
                return ResourceManager.GetString("ToolBar.Open.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reload on Save.
        /// </summary>
        public static string ToolBar_ReloadOnSave {
            get {
                return ResourceManager.GetString("ToolBar.ReloadOnSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To ensure you do not delete changes made externally, you can reload the documents right before they are to be saved.
        /// </summary>
        public static string ToolBar_ReloadOnSave_ToolTip {
            get {
                return ResourceManager.GetString("ToolBar.ReloadOnSave.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string ToolBar_Save {
            get {
                return ResourceManager.GetString("ToolBar.Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save the current Office document.
        /// </summary>
        public static string ToolBar_Save_ToolTip {
            get {
                return ResourceManager.GetString("ToolBar.Save.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string ToolBar_Settings {
            get {
                return ResourceManager.GetString("ToolBar.Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View the editor settings.
        /// </summary>
        public static string ToolBar_Settings_ToolTip {
            get {
                return ResourceManager.GetString("ToolBar.Settings.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show space, tab and line end characters in the editor.
        /// </summary>
        public static string ToolBar_ShowWhitespaces_ToolTip {
            get {
                return ResourceManager.GetString("ToolBar.ShowWhitespaces.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment / uncomment the currently selected lines.
        /// </summary>
        public static string ToolBar_ToggleComment_ToolTip {
            get {
                return ResourceManager.GetString("ToolBar.ToggleComment.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validate.
        /// </summary>
        public static string ToolBar_Validate {
            get {
                return ResourceManager.GetString("ToolBar.Validate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check whether the current XML file conforms to its corresponding schema.
        /// </summary>
        public static string ToolBar_Validate_ToolTip {
            get {
                return ResourceManager.GetString("ToolBar.Validate.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to v{0} Avalilable!.
        /// </summary>
        public static string ToolBar_VersionAvailable {
            get {
                return ResourceManager.GetString("ToolBar.VersionAvailable", resourceCulture);
            }
        }
    }
}
