//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CustomUIEditor.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SchemasResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SchemasResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CustomUIEditor.Resources.SchemasResource", typeof(SchemasResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; ?&gt;
        ///&lt;!--
        ///	Schema definition for Ribbon Extensibility
        ///
        ///	Copyright (c) Microsoft Corporation. All rights reserved.
        ///--&gt;
        ///&lt;xsd:schema xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot; version=&quot;1.0&quot; 
        ///	targetNamespace=&quot;http://schemas.microsoft.com/office/2006/01/customui&quot;
        ///						xmlns=&quot;http://schemas.microsoft.com/office/2006/01/customui&quot;
        ///	elementFormDefault=&quot;qualified&quot;
        ///	attributeFormDefault=&quot;unqualified&quot;
        ///&gt;
        ///  &lt;xsd:annotation&gt;
        ///    &lt;xsd:documentation&gt;
        ///      -------------------------------- [rest of string was truncated]&quot;;.
        /// </summary>
        public static string customUI {
            get {
                return ResourceManager.GetString("customUI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; ?&gt;
        ///&lt;!--
        ///	Schema definition for Ribbon Extensibility
        ///
        ///	Copyright (c) Microsoft Corporation. All rights reserved.
        ///--&gt;
        ///&lt;xsd:schema xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot; version=&quot;1.0&quot; 
        ///	targetNamespace=&quot;http://schemas.microsoft.com/office/2009/07/customui&quot;
        ///	xmlns=&quot;http://schemas.microsoft.com/office/2009/07/customui&quot;
        ///	elementFormDefault=&quot;qualified&quot;
        ///	attributeFormDefault=&quot;unqualified&quot;
        ///&gt;
        ///	&lt;xsd:annotation&gt;
        ///		&lt;xsd:documentation&gt;
        ///			------------------------------------------- [rest of string was truncated]&quot;;.
        /// </summary>
        public static string customui14 {
            get {
                return ResourceManager.GetString("customui14", resourceCulture);
            }
        }
    }
}
